sonar.projectKey=taskmanager-frontend
sonar.projectName=TaskManager Frontend
sonar.projectVersion=0.1.0

sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.javascript.lcov.reportPaths=coverage/taskmanager-frontend/lcov.info
